### PR TITLE
Support Persian language!

### PR DESCRIPTION
**Pull request by BaseMax**
Hey @Microsoft,

I'm Max. (https://github.com/BaseMax)
We have translated the README file as the Persian language. (Farsi,  فارسی, پارسی)

With all love for the people of Iran. @bitcrazed

Regards,
Max Base, Asrez team

### CODE REVIEW

**Comment by BaseMax** [comment]
Hey,

Can someone check and review it? @bitcrazed @ggurbet @LiTO773

Regards,
Max

**Comment by ggurbet** [comment]
Seems OK to me. However I do not have write access to this repository, so someone from Microsoft should approve it. It may take a while, so please be patient :)

**Comment by BaseMax** [comment]
Hello,

They haven't informed me yet. and nobody has reviewed the files. 
Where are the administrators? @bitcrazed @ggurbet @LiTO773
Is anything going to happen?

Best,
Max

**Comment by microsoftopensource** [comment]
Thanks for taking the time to contribute this localization pull request. However, we are not able to accept contributions to this historical reference repository at this time.

**Pull request closed without merging**
