### PR TITLE
Added Russian Translation to Readme

### PR DESCRIPTION
**Pull request by Akshay090**
#Hacktoberfest2018

### CODE REVIEW

**Comment by Phikimon** [comment]
This is the result of autotranslation and definitely should not be merged.

**Comment by dartess** [comment]
this is terrible

**Comment by sirkadirov** [comment]
@dartess yeah... Hacktoberfest is a good idea, but something always goes wrong... :disappointed:

**Comment by sirkadirov** [comment]
I'll create a new PR with acceptable translation. I think this step would be better than changing translation in this PR.

**Pull request closed without merging**
