### PR TITLE
Hacktoberfest 2018

### PR DESCRIPTION
**Pull request by ChristianFaris2000**
Information on our partnership is here.

Microsoft is participating in this year’s Hacktoberfest! If you make at least one pull request on any Microsoft repo between October 1st – 31st, you’ll receive a limited edition t-shirt designed by Ashley McNamara (Cloud Developer Advocate and graphic designer). You can find more details here.

### CODE REVIEW

**Comment by balcsida** [comment]
Aaand I opened my PR on September 30th 😿

**Comment by lreneral** [comment]
There is no link

**Comment by sundhaug92** [comment]
Link should be either https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/ or https://hacktoberfest.digitalocean.com

**Comment by bitcrazed** [comment]
Sorry - no link, no play ;)

**Pull request closed without merging**
