### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by kfarwell**
just cleaning up some old cruft

### CODE REVIEW

**Comment by Sarkie** [comment]
You raised a pr to remove everything?

Mad lad.

**Comment by fdrobidoux** [comment]
Oh come on. MS tries to release stuff for free and you just screw with them and waste their time. Not cool.

**Comment by bitcrazed** [comment]
Thanks for your PR, but as stated in the [readme](README.md), we're not accepting changes to the code ;)

**Comment by kenshen112** [comment]
And, all he was trying to do was clean up some old code.

**Comment by KakolIsSomewhatGay** [comment]
funi

**Comment by franklixuefei** [comment]
This is a good way to get famous ma good lad

**Comment by ovflowd** [comment]
I like some good jokes. But in this case, that's likely not _okey_ creating a PR like that.

Most likely this PR disrespects works of thousand of developers that created MS-DOS. Not talking that MS-DOS for the concepts of today, it's _deprecated_ and bad.

But see, in the past MS-DOS was the future. And most likely the source code was following the best standards of that era.

I would really like for people not making this kind of jokes in open source. Because even if open source stands for collaborating and fun, it doesn't seem stands for making fun of the code of contributors.

This PR doesn't helps or contributes in anything, only disrespects the owners and contributors.

Sorry for the big text.

**Pull request closed without merging**
