### PR TITLE
Translated the README to dutch.

### PR DESCRIPTION
**Pull request by artus**
Dutch is spoken not only in western-europe but also in various countries and islands in Central and South America. Therefore I think it would be nice to add this translation.

Also, why is Bill Gates not in the list of contributors? 🎉🎉

### CODE REVIEW

**Comment by llcasel** [comment]
rumour is bill borrowed some stuff from atari, dont think he programmed much. hes a good salesman.

**Comment by llcasel** [comment]
im new to github, but seeing a dutch editor here motivated me to leave a comment, dutch, frisian,  german, and  english are my first 4 languages, not sure if this comment gets anywhere ; ))

**Comment by artus** [comment]
Hi @llcasel , if you want to translate some stuff for people, look up on how a pull request works and you can start doing some work! I think a lot of repositories are in need of a dutch translator :)

**Comment by microsoftopensource** [comment]
Thanks for taking the time to contribute this localization pull request. However, we are not able to accept contributions to this historical reference repository at this time.

**Pull request closed without merging**
